In [2]:
from mlchem.chem.manipulation import (MolGenerator,
                                      MolCleaner)

# Load your list of SMILES
# Here, dataset is generated for demonstrative purposes
generator = MolGenerator()
generator.generate_smiles(template_string='CCCN',
                          n_molecules=100,
                          n_fragments=5,
                          n_substitutions=10,
                          attempt_limit=5000,
                          include_extremities=True)

# Show that the generated SMILES retain the initial template
display(generator.smiles_generated[:5])

# Perform all cleaning steps
cleaner = MolCleaner(input_smiles_list=generator.smiles_generated)
cleaner.full_clean()

['CCCCN(C)CC#CN', 'C1=NCC1', 'CC1CCNC=N1', 'CCCNC', 'C=C=[N+]CCC=[N+]']

Initialising SMILES
Removing carbon ions
Removing inorganics
Removing organometallics
Desalting SMILES
Neutralising SMILES
Performing quality check
DONE

In [3]:
cleaner.df_accepted

,id,SMILES,PRIORITY,MESSAGES
0,0,CCCCN(C)CC#CN,0,ok
1,1,C1=NCC1,0,ok
2,2,CC1CCNC=N1,2,[InChI: Omitted undefined stereo]
3,3,CCCNC,0,ok
4,4,C=C=[N+]CCC=[N+],6,[molecule has a radical that is not found in t...
...,...,...,...,...
96,96,CCCCC#CCCCCCN,0,ok
97,97,CCC=NSCCCN,2,[InChI: Omitted undefined stereo]
98,98,CCC=NSNCCCSCCCN,2,[InChI: Omitted undefined stereo]
99,99,CCCC=CCCC=NSNCCCSCCCN,2,[InChI: Omitted undefined stereo]
100,100,CCCC(C)CCCC=NSNCCCSCCCN,2,[InChI: Omitted undefined stereo]

In [4]:
cleaner.df_rejected

Empty DataFrame
Columns: [id, SMILES, rejection]
Index: []

In [5]:
# molecules that need closer inspection
cleaner.df_accepted[cleaner.df_accepted.PRIORITY>=7]

,id,SMILES,PRIORITY,MESSAGES
5,5,[N+]C=CCCCCCN,12,[molecule has a radical that is not found in t...
18,18,N=[N+]C1C=C1C=C=CCNC=CCCNC=O,8,[molecule has a radical that is not found in t...
30,30,CN=C[N+]CCC(C)OCCCCCN,8,[molecule has a radical that is not found in t...
32,32,C1=NCCCCCCO1,7,"[molecule has a crossed bond in a ring, InChI:..."
35,35,CCC=CC=[N+]C=CCCCN,8,[molecule has a radical that is not found in t...
36,36,CCC=CC=CCCCC=[N+]C=CCCCN,8,[molecule has a radical that is not found in t...
37,37,C=[SH](C)(C)C=CCCCC=[N+]C=CCCCN,8,[molecule has a radical that is not found in t...
38,38,CC(C)(C=CCCCC=[N+]C=CCCCN)C1=CS1,8,[molecule has a radical that is not found in t...
39,39,CSCC(=[N+])C(C)(C)C=CCCCC=[N+]C=CCCCN,8,[molecule has a radical that is not found in t...
57,57,CCCCCCNC1CCC=CCCC=C(C)OO1,7,"[molecule has a crossed bond in a ring, InChI:..."
58,58,CCCCCCNC1OOC(C)=CCC2CC=CCC21,7,"[molecule has a crossed bond in a ring, InChI:..."
93,93,CCC=CCC[N],8,[molecule has a radical that is not found in t...
94,94,CC=CCC(C)CCC[N],8,[molecule has a radical that is not found in t...
95,95,CC(CC=CCCC=CCO)CCC[N],8,[molecule has a radical that is not found in t...

In [6]:
# less problematic molecules
cleaner.df_accepted[cleaner.df_accepted.PRIORITY<7]

,id,SMILES,PRIORITY,MESSAGES
0,0,CCCCN(C)CC#CN,0,ok
1,1,C1=NCC1,0,ok
2,2,CC1CCNC=N1,2,[InChI: Omitted undefined stereo]
3,3,CCCNC,0,ok
4,4,C=C=[N+]CCC=[N+],6,[molecule has a radical that is not found in t...
...,...,...,...,...
96,96,CCCCC#CCCCCCN,0,ok
97,97,CCC=NSCCCN,2,[InChI: Omitted undefined stereo]
98,98,CCC=NSNCCCSCCCN,2,[InChI: Omitted undefined stereo]
99,99,CCCC=CCCC=NSNCCCSCCCN,2,[InChI: Omitted undefined stereo]
100,100,CCCC(C)CCCC=NSNCCCSCCCN,2,[InChI: Omitted undefined stereo]